# -*- coding: utf-8 -*-
"""PANDAS_CC_D2_William.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNUAhjYuarIZi5zHw8UltZrEMuHv7rm4

***MANIPULAÇÃO DE DADOS COM PANDAS - ESTRUTURA DE DADOS COM LISTA, TUPLA E DICIONÁRIO***

`*Documentação disponível em:* https://pandas.pydata.org/docs/`
"""

import pandas as pd # importa a biblioteca 'Pandas'.
#                     Uma das estruturas de dados mais utilizadas no pandas é o DataFrame.
#                     Uma instância do tipo DataFrame é um pbjeto de duas (ou mais) dimensões com as seguintes características:
#                  -- Suas dimensões podem ser modificadas decorrente da modificação dos dados.
#                  -- Seus dados podem ser acessados através de rótulos ao invés de exclusivamente por índices.
#                  -- É também possível trabalhar com dados heterogêneos, tanto nas linhas como também nas colunas.

# Criando um DataFrame a partir de uma lista de tuplas:

nomes = ['William', 'Breno', 'Elizabeth']
idades = [19, 20, 20]
dados = list(zip(nomes, idades)) # transforma as duas listas em tupla
print(dados)
df = pd.DataFrame(data = dados) # ---> comando do pandas
print(df)

#dados = classe // nome, idades = objetos

# Criando DataFrames a partir de um Dicionário:

import pandas as pd
dicionario = { 'Identificação' : ['William', 'Breno', 'Cleslley', 'Lazim', 'Victor', 'Elizabeth', 'César'],
               'Idade' : [19, 21, 21, 20, 20, 20, 19]
             }
df = pd.DataFrame(data=dicionario)
print(df)

import pandas as pd
dados = [('William', 19), ('Bianca', 20), ('Asafe', 27)]
colunas = ['Nome', 'Idade']
linhas = ['A', 'B', 'C']
df = pd.DataFrame(dados, columns = colunas, index = linhas)
print(df)

print(list(df.index))
print(list(df.columns))
print(df.ndim)
print(df.shape)
print(df.size)
print(df.empty)

df.columns = ['Identificação', 'Idade']
df.index = ['Linha1','Linha2','Linha3']

# Proposta de exercício de Data Frame: Dados de músicas de uma plataforma de streaming
import pandas as pd

nome_musicas = ["Dear my friend", "Wildflower", "Can't catch me now", "Dead Man", "Definition of ugly is", "Daylight", "Dial Drunk", "Someone New", "Merry Christmas Mr.Lawrence", "Overjoyed", "Ilomilo"]
artistas = ["Agust D", "RM", "Olivia Rodrigo", "David Kushner", "The Rose", "David Kushner", "Noah Kahan", "Laufey", "Ryuchi Sakamoto", "Bastille", "Billie Eilish"]
genero = ["HipHop", "HipHop", "Pop", "Alternative", "Kpop", "Alternative", "Alternative", "Jazz", "Clássica", "Pop", "Pop"]
ano_lancamento = [2020, 2022, 2023, 2023, 2022, 2023, 2022, 2021, 1996, 2013, 2019]
duracao_musica = [4.5, 4.3, 3.2, 4.3, 3.5, 3.3, 3.3, 3.1, 4.4, 3.2, 2.3]

dados_musicais = {
    'Música': nome_musicas,
    'Artista': artistas,
    'Gênero': genero,
    'Ano de lançamento': ano_lancamento,
    'Duração (segundos)' : duracao_musica,
}

musica_df = pd.DataFrame(dados_musicais)
print(musica_df)
print()

# a) Mais ouvidas
print("a) Mais ouvidas: ")
mais_ouvida = musica_df.loc[musica_df['Ano de lançamento'].idxmax()]['Música']
print(mais_ouvida)
print()
# b) Artista com mais músicas
print("b) Artistas com mais músicas:")
artista_mais_musicas = musica_df['Artista'].mode()[0]
print(artista_mais_musicas)
print()
# c) Gênero mais ouvido
print("c) Gênero mais popular:")
genero_mais_popular = musica_df['Gênero'].mode()[0]
print(genero_mais_popular)
print()
# d) Música mais recente
print("d) Música mais recente:")
musica_mais_recente = musica_df.loc[musica_df['Ano de lançamento'].idxmax()]['Música']
print(musica_mais_recente)
print()
# e) Adicionar nova coluna com duração de segundos
print("e) Duração (segundos):")
musica_df['Duração (segundos)'] = musica_df['Duração (segundos)'] * 60
print(musica_df)
print()
print(musica_df.shape)
display(musica_df)

#Proposta 2: Dados de Estudantes de uma Escola

#a) Média de Notas
#b) Aluno com maior nota em Estrutura de Dados
#c) Aluno mais novo
#d) Aluno com menor nota em Banco de Dados
#e) Adicionar uma nova coluna com a média geral das notas import pandas as pd

import pandas as pd

aluno = ["William", "Breno", "Lazim", "César", "Elizabeth"]
notaEd1 = [9, 7, 5, 6, 6]
notaEd2 = [10, 9, 7, 10, 8]
notaBd1 = [8, 6, 5, 10, 7]
notaBd2 = [9, 9, 8, 9, 8]
data_nasc_aluno = [2003, 2003, 2002, 2004, 2000]

dados_alunos = {
    'Alunos' : aluno,
    'Nota ED 1' : notaEd1,
    'Nota ED 2' : notaEd2,
    'Nota BD 1' : notaBd1,
    'Nota BD 2' : notaBd2,
    'Idade' : data_nasc_aluno,
}

estudantes_df = pd.DataFrame(dados_alunos)
print(estudantes_df)
print()

#a) Média de Notas
print("a) Média de notas de Estrutura de Dados: ")
media_notas = (estudantes_df['Nota ED 1'] + estudantes_df['Nota ED 2']) / 2
print(media_notas)
print()
print("Média de notas de Banco de Dados: ")
media_notas = (estudantes_df['Nota BD 1'] + estudantes_df['Nota BD 2']) / 2
print(media_notas)
print()

#b) Aluno com maior nota em Estrutura de Dados
print("b) Aluno com maior nota em Estrutura de Dados: ")
estudantes_df['Média ED'] = (estudantes_df['Nota ED 1'] + estudantes_df['Nota ED 2']) / 2
aluno_maior_nota_ed = estudantes_df.loc[estudantes_df['Média ED'].idxmax()]['Alunos']
print(aluno_maior_nota_ed)
print()
print("Aluno com maior nota em Banco de Dados: ")
estudantes_df['Média BD'] = (estudantes_df['Nota BD 1'] + estudantes_df['Nota BD 2']) / 2
aluno_maior_nota_bd = estudantes_df.loc[estudantes_df['Média BD'].idxmax()]['Alunos']
print(aluno_maior_nota_bd)
print()

#c) Aluno mais novo
print("c) Aluno mais novo: ")
aluno_mais_novo = estudantes_df.loc[estudantes_df['Idade'].idxmax()]['Alunos']
print(aluno_mais_novo)
print()

#d) Aluno com menor nota em Banco de Dados
print("d) Aluno com menor nota em Banco de Dados: ")
estudantes_df['Média BD'] = (estudantes_df['Nota BD 1'] + estudantes_df['Nota BD 2']) / 2
aluno_menor_nota_bd = estudantes_df.loc[estudantes_df['Média BD'].idxmin()]['Alunos']
print(aluno_menor_nota_bd)
print()

#e) Adicionar uma nova coluna com a média geral das notas import pandas as pd
print("e) Adicionar uma nova coluna com a média geral das notas: ")
estudantes_df['Média Geral'] = (estudantes_df['Nota ED 1'] + estudantes_df['Nota ED 2'] + estudantes_df['Nota BD 1'] + estudantes_df['Nota BD 2']) / 4
print(estudantes_df)
print()

'''Atividade Avaliativa dia 03/05 Pandas'''
#Dados de Alunos de uma Escola:
import pandas as pd

aluno = ["Breno", "Cleslley", "William"]
serie = ["3º ano", "3º ano", "3º ano"]
nota1 = [9, 9, 9]
nota2 = [10, 9, 7]
idade_aluno = [21, 20, 19]

dados_alunos = {
    'Nome' : aluno,
    'Série' : serie,
    'Primeira Nota' : nota1,
    'Segunda Nota' : nota2,
    'Idade' : idade_aluno
}

estudantes_df = pd.DataFrame(dados_alunos)
print(estudantes_df)
print()

print("Média Final: ")
media_notas = (estudantes_df['Primeira Nota'] + estudantes_df['Segunda Nota']) / 2
print(media_notas)
print()

# a) Quantas colunas o DataFrame possui?
print("a) Quantas colunas o DataFrame possui? ")
cols = estudantes_df.shape[0]
print("Columns: " + str(cols))

# b) Qual é o nome da segunda pessoa na lista?
print("b) Qual é o nome da segunda pessoa na lista? ")
nome_segunda_pessoa = estudantes_df.iloc[1]['Nome']
print(nome_segunda_pessoa)

# c) Qual é a média das idades?
print("c) Qual é a média das idades? ")
media_idades = estudantes_df['Idade'].mean()
print("Média das idades: " + str(media_idades))

# d) Qual é a Série do terceiro indivíduo da lista?
print("d) Qual é a Série do quarto indivíduo da lista? ")
print(estudantes_df.iloc[2][1])

# e) Adicione uma nova pessoa ao DataFrame.
print("e) Adicione uma nova pessoa ao DataFrame. ")
nova_pessoa = {
    'Nome': 'Kadidja',
    'Série': '3º ano',
    'Primeira Nota': 8,
    'Segunda Nota': 9,
    'Idade': 25
}
estudantes_df = pd.concat([estudantes_df, pd.DataFrame(nova_pessoa, index=[3])], ignore_index=True)
print(estudantes_df)

# f) Remova a terceira pessoa do DataFrame.
print(" f) Remova a terceira pessoa do DataFrame.")
estudantes_df = estudantes_df.drop(3)
print(estudantes_df)
print(estudantes_df.shape)
display(estudantes_df)